import { Project } from "../types";

export const projectsConfig: Project[] = [
  {
    title: "Vexal.io",
    link: "https://www.vexal.io/",
    description: "Automation tool built for automating developer workflow.",
    tags: [
      "Go",
      "OAuth2.0",
      "Open Source",
      "Open Ai",
      "GCP",
      "CLI",
      "Firebase",
      "Homebrew",
      "Cobra-CLI",
      "Automation",
    ],
    status: "Released",
  },
  {
    title: "Zvite.io",
    description:
      "Invitation system designed ease of use and to promote in-person events.",
    link: "https://www.zvite.io/",
    tags: [
      "React",
      "NextJS",
      "Node",
      "Typescript",
      "Stripe",
      "SupaBase",
      "Atomic Design",
    ],
    status: "In Progress",
  },
  {
    title: "Vexal Server",
    description: "Open Source Web template",
    link: "https://www.pinedavictor.com/",
    tags: ["OAuth2.0", "React", "Open Source", "NextJS", "Node", "Typescript"],
    status: "Released",
  },
  {
    title: "a la mode",
    description: "Open Source Web template",
    link: "https://www.pinedavictor.com/",
    tags: ["React", "ViteJS", "Node", "Typescript", "Atomic Design"],
    status: "Released",
  },
  {
    title: "Durtles",
    description: "Open Source Python CLI for editing directories",
    link: "https://github.com/PinedaVictor/Durtles",
    tags: [
      "Python",
      "Open Source",
      "OOP",
      "Automation",
      "Directory Utils",
      "CLI",
    ],
    status: "Repository",
  },
  {
    title: "Glitch Landing Page",
    description: "Open Source Animated Landing page app",
    link: "https://github.com/PinedaVictor/Glitch-Landing-Page",
    tags: ["React", "Open Source", "Node", "Typescript", "Atomic Design"],
    status: "Repository",
  },
  {
    title: "Portfolio Template",
    description: "Open source deveoper portfolio app",
    link: "https://github.com/PinedaVictor/webfolio",
    tags: [
      "React",
      "Open Source",
      "Node",
      "Typescript",
      "Firebase Cloud Functions",
    ],
    status: "Archived",
  },
];
