/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TravelGuidesLazyRouteImport = createFileRoute('/travel-guides')()
const TravelLazyRouteImport = createFileRoute('/travel')()
const ReferencesLazyRouteImport = createFileRoute('/references')()
const ProjectsLazyRouteImport = createFileRoute('/projects')()
const IndexLazyRouteImport = createFileRoute('/')()

const TravelGuidesLazyRoute = TravelGuidesLazyRouteImport.update({
  id: '/travel-guides',
  path: '/travel-guides',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/travel-guides.lazy').then((d) => d.Route))
const TravelLazyRoute = TravelLazyRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/travel.lazy').then((d) => d.Route))
const ReferencesLazyRoute = ReferencesLazyRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/references.lazy').then((d) => d.Route))
const ProjectsLazyRoute = ProjectsLazyRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/references': typeof ReferencesLazyRoute
  '/travel': typeof TravelLazyRoute
  '/travel-guides': typeof TravelGuidesLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/references': typeof ReferencesLazyRoute
  '/travel': typeof TravelLazyRoute
  '/travel-guides': typeof TravelGuidesLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/references': typeof ReferencesLazyRoute
  '/travel': typeof TravelLazyRoute
  '/travel-guides': typeof TravelGuidesLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/references' | '/travel' | '/travel-guides'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/references' | '/travel' | '/travel-guides'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/references'
    | '/travel'
    | '/travel-guides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  ReferencesLazyRoute: typeof ReferencesLazyRoute
  TravelLazyRoute: typeof TravelLazyRoute
  TravelGuidesLazyRoute: typeof TravelGuidesLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-guides': {
      id: '/travel-guides'
      path: '/travel-guides'
      fullPath: '/travel-guides'
      preLoaderRoute: typeof TravelGuidesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  ReferencesLazyRoute: ReferencesLazyRoute,
  TravelLazyRoute: TravelLazyRoute,
  TravelGuidesLazyRoute: TravelGuidesLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
